timeout: 120000s
substitutions:
  _CUSTOM_REGION: us-west2-a
  _CUSTOM_CLUSTER: hasura-k8s
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
    - '-c'
    - >-
      docker pull gcr.io/hasura-342723/big-dipper-v1:latest
      || exit 0
steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: Write Secrets to Env
    entrypoint: bash
    args: 
      - -c
      - |
        sed -i 's/mongoUrlVal/$$(gcloud beta secrets versions access --secret=mongourl latest)/g' ./deploy/pylons-big-dipper/values.yaml
    # secretEnv: ['MONGO_URL']
  # availableSecrets:
  #   secretManager:
  #   - versionName: 'projects/430696988038/secrets/mongourl/versions/latest'
  #     env: MONGO_URL
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - .
      - -t
      - gcr.io/hasura-342723/big-dipper-v1
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - 'gcr.io/hasura-342723/big-dipper-v1'
  id: PushLatest
  - name: gcr.io/cloud-builders/kubectl
    id: Configure kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config

  - name: gcr.io/$PROJECT_ID/helm
    id: Deploy chart
    args:
      - upgrade
      - -i
      - big-dipper-v1
      - ./deploy/pylons-big-dipper
      - -f
      - ./deploy/pylons-big-dipper/values.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true
options:
  logging: CLOUD_LOGGING_ONLY

