name: Deploy for Testnet

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    branches: [staging]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: staging

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: |
            helm upgrade pylons-big-dipper \
              --install \
              --namespace pylons \
              --set image=ghcr.io/pylons-tech/big-dipper:staging \
              --set pullSecret=regcred \
              ./helm/pylons-big-dipper
